// GENERATED by @motu/codegen from motu-manifest.json — do not edit.
import { call } from '@motu/runtime';

export const MemberService = {
  search: (page: number, parameters: Record<string, unknown>) =>
    call<{ list: Record<string, unknown>[]; first: string; perPage: string; size: string }>('MemberService', 'search', [page, parameters]),
};

export const CompanyGroupService = {
  search: (page: number, parameters: Record<string, unknown>) =>
    call<{ list: Record<string, unknown>[]; first: string; perPage: string; size: string }>('CompanyGroupService', 'search', [page, parameters]),
};

export const __roles: Record<string, string[]> = {
  "MemberService.search": [
    "MEMBER_READ"
  ],
  "CompanyGroupService.search": [
    "COMPANY_READ"
  ]
};
