// The Next host's contribution to the lagoon's Vite config.
//
// This is host-adapter knowledge, not project configuration, which is why it lives here rather than in
// every adopting project's vite.config.ts: mapping `next/*` to inert stubs, speaking the host's `@/…`
// alias, and loading the host's own Tailwind are true of EVERY Next project motu is dropped into.
// A project declares only what is genuinely its own — module stand-ins and browser env — in
// lagoon.config.json.
import { resolve, dirname } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * The lagoon's Tailwind setup — the HOST's config, with one thing changed, GENERATED into `.motu/cache`
 * rather than committed.
 *
 * Tailwind resolves `content` globs against the current working directory, and here that is the lagoon
 * rather than the app. The host's own './components/**' globs would therefore match nothing, Tailwind
 * would emit no utilities at all, and every island would render unstyled — a preview that quietly lies
 * about how the component looks in the app. Re-anchoring the globs on the host root fixes that, and the
 * island sources are added so a class used ONLY inside an island still gets generated. Everything else
 * (theme, plugins, dark mode, breakpoints) is inherited, so the lagoon and the app cannot drift apart
 * on design tokens.
 *
 * It is written to disk rather than passed as an object because Tailwind's own loader is what handles a
 * host config that `require()`s CJS plugins — hand it a path and that keeps working; hand it an
 * imported object and the ESM bundling that breaks on is back.
 */
/**
 * The host's own Tailwind config, if it has one.
 *
 * A Next app does not necessarily use Tailwind, and this adapter used to assume it did: the postcss
 * plugin was installed unconditionally and pointed at `<hostRoot>/tailwind.config`, so a Next host
 * without one got a lagoon that 500s on the first CSS request with "Cannot find module" naming a
 * generated file the project never wrote. Found by motu's own lagoon host, which is deliberately
 * Tailwind-free — peps, the adapter's only other consumer, has Tailwind, so nothing had ever asked.
 */
function hostTailwindConfig(paths) {
  for (const name of ['tailwind.config.ts', 'tailwind.config.js', 'tailwind.config.mjs', 'tailwind.config.cjs']) {
    const candidate = resolve(paths.hostRoot, name);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function generateTailwindConfig(paths) {
  mkdirSync(paths.cacheDir, { recursive: true });
  const out = resolve(paths.cacheDir, 'tailwind.lagoon.config.ts');
  writeFileSync(
    out,
    `// GENERATED by motu (@motu/adapter-next). Do not edit; do not commit.
import { resolve } from 'node:path';
import hostConfig from ${JSON.stringify(resolve(paths.hostRoot, 'tailwind.config'))};

const HOST_ROOT = ${JSON.stringify(paths.hostRoot)};
const hostContent = Array.isArray(hostConfig.content) ? hostConfig.content : (hostConfig.content?.files ?? []);

export default {
  ...hostConfig,
  content: [
    ...hostContent.map((glob) => (typeof glob === 'string' ? resolve(HOST_ROOT, glob) : glob)),
    ${JSON.stringify(resolve(paths.appRoot, 'src/**/*.{ts,tsx}'))},
  ],
};
`,
  );
  return out;
}

export async function contribute({ paths, lagoonJson, resolveBuildDep }) {
  // Only when the HOST has one. See hostTailwindConfig: assuming it did is what made this adapter
  // unusable on a Next app that styles itself any other way.
  const usesTailwind = hostTailwindConfig(paths) !== null;
  const tailwindcss = usesTailwind ? await resolveBuildDep('tailwindcss') : null;
  const autoprefixer = await resolveBuildDep('autoprefixer');
  const stubs = resolve(HERE, 'lagoon/next-stubs.tsx');

  return {
    define: {
      // The host application's modules read process.env AT IMPORT TIME — a Supabase client that throws
      // when its keys are missing is enough to take the whole lagoon down before anything renders, and
      // the error ("process is not defined") says nothing about why. There is no backend here, so the
      // values only have to exist: declare them under "env" in lagoon.config.json. Never put a real
      // secret there — the lagoon gets published as a static page.
      'process.env': JSON.stringify({ NODE_ENV: 'development', ...(lagoonJson.env ?? {}) }),
    },
    alias: [
      // (the framework's own @motu/* aliases are added unconditionally by buildLagoonViteConfig)
      // Project aliases from lagoon.config.json "alias" — BEFORE the host's own '@/…' rule, because the
      // first matching entry wins and '^@/' would otherwise rewrite the specifier to the real module
      // before this ever sees it. This is the seam for standing a host module down inside the lagoon —
      // a React context whose real provider talks to a backend, a service module that fetches on import
      // — without touching the component that consumes it. Paths are relative to the lagoon root.
      ...Object.entries(lagoonJson.alias ?? {}).map(([find, replacement]) => ({
        find,
        replacement: resolve(paths.lagoonDir, replacement),
      })),
      // The lagoon mounts components written for the Next app, so it speaks the same module language:
      // the host's '@/…' alias, and next/* mapped to inert stubs.
      { find: /^@\//, replacement: paths.hostRoot + '/' },
      { find: /^next\/link$/, replacement: stubs },
      { find: /^next\/image$/, replacement: stubs },
      { find: /^next\/navigation$/, replacement: stubs },
    ],
    css: {
      postcss: {
        plugins: [
          ...(usesTailwind ? [tailwindcss({ config: generateTailwindConfig(paths) })] : []),
          autoprefixer(),
        ],
      },
    },
  };
}
