// What the REGION side of a project needs generated.
//
// WHY THIS FILE EXISTS AT ALL, and it is a correction. Coverage's deployment config —
// `configureCoverage({ enabled, regions })` — used to be emitted into the ISLAND registry by
// `motu island sync`. Nothing about it is island-shaped: `regions: ["actions"]` names regions, and the
// two other pieces of coverage already live where they belong (`coverage: { enums }` is declared on
// the archipelago, and `offerRegionToCoverage` is called by `defineArchipelago`).
//
// It went there because the island registry was the one generated module an application is guaranteed
// to import and execute at startup. That is a fact about which files happened to exist, not a reason,
// and it made `motu island sync` quietly responsible for something outside its own noun.
//
// A SEPARATE FILE RATHER THAN A HAND-OWNED ONE. `archipelagos/registry.ts` is scaffolded once and
// edited by `motu archipelago create` — it is the project's, and generated content inside it would
// blur the line that says a generated file is never hand-edited. So this writes its own neighbour and
// the registry imports it.
//
// WRITTEN EVEN WHEN COVERAGE IS OFF, as an empty module. The load-bearing property is that a project
// with coverage off never NAMES `@motu/coverage` — a module nothing imports is a module no bundler
// ships. An empty generated file satisfies that while keeping the registry's import line constant, so
// turning coverage on and off never edits a hand-owned file.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export const COVERAGE_MODULE = 'coverage.generated.ts';

/** The import the archipelago registry needs, exactly as it must appear. */
const IMPORT_LINE = "import './coverage.generated';";

export function renderCoverageModule(coverage) {
  const head = `// GENERATED by \`motu archipelago sync\` — do not edit.
//
// Region-level deployment facts from motu.config.json. Imported for its SIDE EFFECT: it configures
// the coverage fold before any region mounts, and exports nothing.
`;
  if (!coverage?.enabled) {
    return `${head}//
// Coverage is off in motu.config.json, so this module is deliberately empty — and empty is the point.
// Nothing here names \`@motu/coverage\`, so no bundler ships it, while the registry's import line
// stays constant whether coverage is on or off. Turning it on never edits a hand-owned file.
export {};
`;
  }
  return `${head}//
// THE IMPORT IS THE SWITCH. \`@motu/coverage\` is its own package precisely so a project with coverage
// off never names it. Core holds only a seam (\`offerRegionToCoverage\`) that stays a dead branch until
// this line fills it.
//
// It arrives by IMPORT rather than as a build constant. \`__MOTU_DEBUG__\` exists so the seam lens'
// whole import tree dead-code-eliminates — the lens must not ship. Coverage is MEANT to ship, so a
// define would only oblige every host's bundler to declare a global or fail with a ReferenceError.
//
// NOT HERE: which of a region's keys are closed sets — that is a fact about the key, declared on the
// archipelago beside it. Nor the ADDRESSES: the lagoon imports this, and a published lagoon is a
// public page, so an endpoint baked here becomes a public string. The application renders those as
// meta tags instead:
//
//   <meta name="motu-coverage-endpoint" content="…" />
//   <meta name="motu-coverage-known"    content="…" />
import { configureCoverage } from '@motu/coverage';

configureCoverage(${JSON.stringify({ enabled: true, ...(coverage.regions ? { regions: coverage.regions } : {}) })});
`;
}

/**
 * Make sure the project's archipelago registry imports the generated module.
 *
 * The registry is HAND-OWNED, so this touches it once and never again: a single import line, added at
 * the top if it is absent, left alone if it is there. `motu archipelago create` already edits this
 * file, so tooling writing one line into it is the established arrangement rather than a new liberty.
 */
function ensureRegistryImports(registryPath) {
  if (!existsSync(registryPath)) return 'no registry';
  const src = readFileSync(registryPath, 'utf8');
  if (src.includes(IMPORT_LINE)) return 'already imported';
  const lines = src.split('\n');
  // After the last import, so the side effect runs in a predictable place and the file still reads
  // top-down. Before any import would work too; after them is where a reader looks for a side effect.
  let last = -1;
  for (let i = 0; i < lines.length; i++) if (/^import\s/.test(lines[i])) last = i;
  const at = last >= 0 ? last + 1 : 0;
  lines.splice(
    at,
    0,
    '// Region-level deployment facts, generated by `motu archipelago sync`. Imported for its side',
    '// effect; it is an empty module when coverage is off.',
    IMPORT_LINE,
  );
  writeFileSync(registryPath, lines.join('\n'));
  return 'import added';
}

/** Write the region-level generated module for a project. Returns what it did. */
export function syncArchipelagos(archipelagosDir, coverage = null) {
  const out = resolve(archipelagosDir, COVERAGE_MODULE);
  writeFileSync(out, renderCoverageModule(coverage));
  const registry = ensureRegistryImports(resolve(archipelagosDir, 'registry.ts'));
  return { path: out, enabled: Boolean(coverage?.enabled), registry };
}
