// Island discovery + the generated element registry.
//
// Two layouts are supported on purpose (C1: the verbose form stays reachable):
//   FLAT    src/islands/<kebab>.island.ts      — exports `element`; evidence in <kebab>.evidence.ts
//   FOLDER  src/islands/<kebab>/element.ts     — the original; the reference ocean still uses it
//
// The registry is GENERATED rather than hand-maintained. It cannot be a glob: the barrel that exports
// it is imported by the host application, and `import.meta.glob` is a Vite feature — Next's bundler
// does not have it. Generating gives the same "adding an island is not an edit" property with static
// imports that every bundler understands, and lets verify detect a registry that has drifted from the
// files on disk.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/** Every island in the project, whichever layout it uses. */
export function listIslands(islandsDir) {
  if (!existsSync(islandsDir)) return [];
  const out = [];
  for (const e of readdirSync(islandsDir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (existsSync(resolve(islandsDir, e.name, 'element.ts')))
        out.push({ kebab: e.name, layout: 'folder', element: resolve(islandsDir, e.name, 'element.ts') });
    } else if (e.name.endsWith('.island.ts') || e.name.endsWith('.island.tsx')) {
      out.push({
        kebab: e.name.replace(/\.island\.tsx?$/, ''),
        layout: 'flat',
        element: resolve(islandsDir, e.name),
      });
    }
  }
  return out.sort((a, b) => a.kebab.localeCompare(b.kebab));
}

/** The exported ElementSpec binding in an island's file (`element` in flat form, `<camel>Element` in folder form). */
export function elementExportName(file) {
  const m = readFileSync(file, 'utf8').match(/export const (\w+)\s*:\s*ElementSpec/);
  return m?.[1] ?? 'element';
}

/** Render the registry from what is on disk. */
export function renderRegistry(islands, islandsDir, isolation, coverage = null) {
  // NO SILENT DEFAULT. Writing `'shadow'` when the caller passed nothing is how this generator put the
  // wrong isolation into a project declaring `light` — the value was missing from the `paths` object,
  // not from the config, and a fallback turned a plumbing bug into a wrong file nobody would question.
  if (isolation !== 'light' && isolation !== 'shadow') {
    throw new Error(
      `motu: renderRegistry needs the project's isolation ('light' or 'shadow'), got ${JSON.stringify(isolation)}. ` +
        `It comes from motu.config.json via \`paths.isolation\`.`,
    );
  }
  const rows = islands.map((i) => {
    const name = elementExportName(i.element);
    // Extensionless. motu's packages declare `moduleResolution: "Bundler"`, and the registry this
    // writes is compiled by the HOST's bundler — where a '.js' specifier pointing at a '.ts' file is
    // a mapping each one has to be told about. webpack has `extensionAlias`; Turbopack has nothing,
    // and an Angular build resolves it only from inside node_modules. Extensionless needs no mapping.
    const spec = i.layout === 'flat' ? `./${i.kebab}.island` : `./${i.kebab}/element`;
    // Local alias when the export name would collide across islands (folder form names them uniquely).
    const local = name === 'element' ? `${i.kebab.replace(/-(\w)/g, (_, c) => c.toUpperCase())}Element` : name;
    const text = readFileSync(i.element, 'utf8');
    const tag = (text.match(/\btag:\s*'([^']+)'/) ?? text.match(/\bisland\(\s*'([^']+)'/))?.[1] ?? i.kebab;
    return { import: `import { ${name}${local !== name ? ` as ${local}` : ''} } from '${spec}';`, local, tag };
  });
  return `// GENERATED by \`motu island sync\` — do not edit by hand.
//
// Static imports, not a glob: this file is re-exported by the project barrel, which the host
// application imports through its own bundler, and \`import.meta.glob\` is Vite-only.
import type { ElementSpec } from '@motu/react';
import { setDefaultIsolation } from '@motu/core';${coverage?.enabled ? `\nimport { configureCoverage } from '@motu/coverage';` : ''}
${rows.map((r) => r.import).join('\n')}

// ISOLATION, from motu.config.json, applied by IMPORTING this file.
//
// The lagoon has always had it — its root is scaffolded with \`setDefaultIsolation(__MOTU_ISOLATION__)\`
// — and a host application had no way to say it at all: \`registerElements\` takes css and a theme and
// nothing else. So a project declaring \`light\` previewed in light DOM and SHIPPED in shadow, which
// changes whether the host's own stylesheet reaches the island. Approving a baseline then means
// approving something the page does not render.
//
// Set here rather than as an argument to \`registerElements\` so no host has to repeat the value and
// no host can disagree with the config: importing the registry is already what a host does, and this
// file is generated, so a stale copy is caught the same way every other drift in it is.
setDefaultIsolation('${isolation}');
${coverage?.enabled ? `
// COVERAGE, from motu.config.json.
//
// THIS IMPORT IS THE SWITCH. \`@motu/coverage\` is a package of its own precisely so that a project
// with coverage off never names it — and a module nothing imports is a module no bundler ships. Core
// only holds a seam (\`offerRegionToCoverage\`) which stays a dead branch until this line fills it.
//
// It arrives by IMPORT rather than as a build constant. \`__MOTU_DEBUG__\` exists so the seam lens'
// whole import tree dead-code-eliminates — the lens must not ship. Coverage is MEANT to ship, so a
// define would only oblige every host's bundler to declare a global or fail with a ReferenceError.
// No application file mentions coverage; this generated one does.
//
// Which of a region's keys are closed sets is NOT here: that is a fact about the key, declared on the
// archipelago beside it. Neither are the ADDRESSES — this file is imported by the lagoon, and a
// published lagoon is a public page, so an endpoint baked here becomes a public string. The page that
// wants coverage renders them as meta tags instead:
//
//   <meta name="motu-coverage-endpoint" content="…" />
//   <meta name="motu-coverage-known"    content="…" />
configureCoverage(${JSON.stringify({
    enabled: true,
    ...(coverage.regions ? { regions: coverage.regions } : {}),
  })});
` : ''}
export const ELEMENT_REGISTRY: ElementSpec[] = [${rows.map((r) => r.local).join(', ')}];

/**
 * Tag -> element spec, as a TYPE. Lets an archipelago check its wiring against the islands it names
 * (\`RegionWiringOk\`) without importing them at runtime — the values above are the registry; this is
 * the same information in a form the compiler can look up by tag.
 */
export interface ElementTypes {
${rows.map((r) => `  '${r.tag}': typeof ${r.local};`).join('\n')}
}
`;
}

/** Write the registry for a project. Returns the path written. */
export function syncRegistry(islandsDir, isolation, coverage = null) {
  const islands = listIslands(islandsDir);
  const out = resolve(islandsDir, 'registry.ts');
  writeFileSync(out, renderRegistry(islands, islandsDir, isolation, coverage));
  return { path: out, count: islands.length };
}
