// Island discovery + the generated element registry.
//
// Two layouts are supported on purpose (C1: the verbose form stays reachable):
//   FLAT    src/islands/<kebab>.island.ts      — exports `element`; evidence in <kebab>.evidence.ts
//   FOLDER  src/islands/<kebab>/element.ts     — the original; the reference ocean still uses it
//
// The registry is GENERATED rather than hand-maintained. It cannot be a glob: the barrel that exports
// it is imported by the host application, and `import.meta.glob` is a Vite feature — Next's bundler
// does not have it. Generating gives the same "adding an island is not an edit" property with static
// imports that every bundler understands, and lets verify detect a registry that has drifted from the
// files on disk.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/** Every island in the project, whichever layout it uses. */
export function listIslands(islandsDir) {
  if (!existsSync(islandsDir)) return [];
  const out = [];
  for (const e of readdirSync(islandsDir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (existsSync(resolve(islandsDir, e.name, 'element.ts')))
        out.push({ kebab: e.name, layout: 'folder', element: resolve(islandsDir, e.name, 'element.ts') });
    } else if (e.name.endsWith('.island.ts') || e.name.endsWith('.island.tsx')) {
      out.push({
        kebab: e.name.replace(/\.island\.tsx?$/, ''),
        layout: 'flat',
        element: resolve(islandsDir, e.name),
      });
    }
  }
  return out.sort((a, b) => a.kebab.localeCompare(b.kebab));
}

/** The exported ElementSpec binding in an island's file (`element` in flat form, `<camel>Element` in folder form). */
export function elementExportName(file) {
  const m = readFileSync(file, 'utf8').match(/export const (\w+)\s*:\s*ElementSpec/);
  return m?.[1] ?? 'element';
}

/** Render the registry from what is on disk. */
export function renderRegistry(islands, islandsDir) {
  const rows = islands.map((i) => {
    const name = elementExportName(i.element);
    // Extensionless. motu's packages declare `moduleResolution: "Bundler"`, and the registry this
    // writes is compiled by the HOST's bundler — where a '.js' specifier pointing at a '.ts' file is
    // a mapping each one has to be told about. webpack has `extensionAlias`; Turbopack has nothing,
    // and an Angular build resolves it only from inside node_modules. Extensionless needs no mapping.
    const spec = i.layout === 'flat' ? `./${i.kebab}.island` : `./${i.kebab}/element`;
    // Local alias when the export name would collide across islands (folder form names them uniquely).
    const local = name === 'element' ? `${i.kebab.replace(/-(\w)/g, (_, c) => c.toUpperCase())}Element` : name;
    const text = readFileSync(i.element, 'utf8');
    const tag = (text.match(/\btag:\s*'([^']+)'/) ?? text.match(/\bisland\(\s*'([^']+)'/))?.[1] ?? i.kebab;
    return { import: `import { ${name}${local !== name ? ` as ${local}` : ''} } from '${spec}';`, local, tag };
  });
  return `// GENERATED by \`motu island sync\` — do not edit by hand.
//
// Static imports, not a glob: this file is re-exported by the project barrel, which the host
// application imports through its own bundler, and \`import.meta.glob\` is Vite-only.
import type { ElementSpec } from '@motu/react';
${rows.map((r) => r.import).join('\n')}

export const ELEMENT_REGISTRY: ElementSpec[] = [${rows.map((r) => r.local).join(', ')}];

/**
 * Tag -> element spec, as a TYPE. Lets an archipelago check its wiring against the islands it names
 * (\`RegionWiringOk\`) without importing them at runtime — the values above are the registry; this is
 * the same information in a form the compiler can look up by tag.
 */
export interface ElementTypes {
${rows.map((r) => `  '${r.tag}': typeof ${r.local};`).join('\n')}
}
`;
}

/** Write the registry for a project. Returns the path written. */
export function syncRegistry(islandsDir) {
  const islands = listIslands(islandsDir);
  const out = resolve(islandsDir, 'registry.ts');
  writeFileSync(out, renderRegistry(islands, islandsDir));
  return { path: out, count: islands.length };
}
