// Scaffold templates for `motu init`. These exist so a fresh project gets a WORKING loop, not just
// a layout: `motu island verify` boots the lagoon root through Vite, so a project without one has
// static checks and no loop at all — which is the half of motu that matters.
//
// Templates are plain strings with {{placeholders}} (not JS template literals) so the generated TS —
// which is full of backticks and ${} of its own — passes through untouched.

/** Substitute {{key}} placeholders. An unknown placeholder is left alone (so it shows up in review). */
export function render(tpl, vars) {
  // TO A FIXPOINT, because a var's VALUE may itself be a template: `envShim` expands to
  // `import '{{envImport}}';`, and `String.replace` never re-scans what it inserted. One pass left
  // that placeholder verbatim in the generated entry files — valid TypeScript, unresolvable module.
  let out = tpl;
  for (let pass = 0; pass < 5; pass++) {
    const next = out.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
    if (next === out) return out;
    out = next;
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
// Project root files (the layout declaration + the registries islands slot into)
// ---------------------------------------------------------------------------------------------

export const ISLANDS_REGISTRY = `// GENERATED by \`motu island sync\` from the islands on disk — do not edit by hand. \`motu island create\`
// adds one import + one row here; the framework turns this into custom-element registrations.
import type { ElementSpec } from '@motu/react';

export const ELEMENT_REGISTRY: ElementSpec[] = [];
`;

export const ARCHIPELAGOS_REGISTRY = `// Registry of the project's archipelagos by id, so a composition root (or the lagoon / CLI) can
// resolve one by name. \`motu archipelago create\` adds one import + one row here.
import type { ArchipelagoConfig } from '@motu/core';

export const ARCHIPELAGOS: Record<string, ArchipelagoConfig> = {};

/** Resolve an archipelago config by id (undefined if unknown). */
export function getArchipelago(id: string): ArchipelagoConfig | undefined {
  return ARCHIPELAGOS[id];
}
`;

export const BARREL = `// Public surface of the project: the element registry and the archipelago configs + resolver.
// Composition roots (and the motu lagoon / CLI harness) import everything they need from here.
export { ELEMENT_REGISTRY } from './islands/registry.js';
export { ARCHIPELAGOS, getArchipelago } from './archipelagos/registry.js';
`;

/** The app package manifest — the lagoon imports the project by NAME, so the name must resolve. */
export const APP_PACKAGE_JSON = `{
  "name": "{{appPackage}}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "exports": {
    ".": "./src/index.ts",
    "./styles.css": "./src/shared/styles.css"
  },
  "dependencies": {
    "@motu/core": "{{motuDep}}",
    "@motu/react": "{{motuDep}}",
    "@motu/runtime": "{{motuDep}}"{{adapterDep}}
  },
  "peerDependencies": {
    "react": ">=18",
    "react-dom": ">=18"
  }
}
`;

/** The one shared island stylesheet. `motu archipelago verify` lints this, so it ships dual-mode. */
export const SHARED_STYLES = `/* Styles for every motu island. In shadow isolation this sheet is adopted into the shadow root; in
   light isolation it is injected once globally and the island root carries a \`.motu-root\` marker.
   That is why every host-scoped rule targets \`:where(:host, .motu-root)\` — a bare \`:host\` is inert
   in light DOM. One sheet, both modes.

   Colours come from --x-* tokens (host-overridable) with --_* locals holding the fallback, so a host
   can reskin islands without either side reopening isolation. */
:where(:host, .motu-root) {
  --_text: var(--x-color-text, inherit);
  --_muted: var(--x-color-muted, #6b7280);
  --_border: var(--x-border, #e5e7eb);
  --_radius: var(--x-radius, 6px);
  --_surface: var(--x-color-surface, #ffffff);
  display: block;
  color: var(--_text);
  font-family: var(--x-font, inherit);
}
`;

/** Build output + local installs. `.motu/` holds published lagoon artifacts, which are rebuilt on
 *  demand and can be large; the lagoon's node_modules is its own build toolchain. */
export const GITIGNORE = `node_modules/
dist/
.motu/
`;

// ---------------------------------------------------------------------------------------------
// Lagoon root — the part `motu island verify` actually boots
// ---------------------------------------------------------------------------------------------

/** The lagoon's OWN dependencies only.
 *
 *  Deliberately does not list @motu/* or the app package: vite.config resolves those by path (they
 *  are unpublished, raw-TS sources), so declaring them here would just be an install that fails.
 *  React is also absent on purpose — it resolves upward to the host application's copy, and a second
 *  React installed here would give the host two of them and break hooks the moment an island renders
 *  a component from the host's own library. */
export const LAGOON_PACKAGE_JSON = `{
  "name": "{{appPackage}}-lagoon",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "focus": "vite --open /lagoon.html",
    "build": "vite build"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.3",
    "vite": "^5.4.10"{{lagoonExtraDevDeps}}
  }
}
`;

export const LAGOON_INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>motu lagoon — {{appPackage}}</title>
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        background: #f6f4f0;
        color: #22302c;
        font-family: ui-sans-serif, system-ui, "Segoe UI", Roboto, sans-serif;
      }
    </style>
  </head>
  <body>
    <div id="lagoon-root"></div>
    <script type="module" src="{{galleryEntrySrc}}"></script>
  </body>
</html>
`;

export const LAGOON_FOCUS_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>motu lagoon — single target (isolated)</title>
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        background: #f6f4f0;
        color: #22302c;
        font-family: ui-sans-serif, system-ui, "Segoe UI", Roboto, sans-serif;
      }
      #lagoon { max-width: 1440px; margin: 22px auto; padding: 0 20px; }
    </style>
  </head>
  <body>
    <div id="lagoon"></div>
    <script type="module" src="{{focusEntrySrc}}"></script>
  </body>
</html>
`;

/**
 * A `process.env` for the browser, installed before any application module is evaluated.
 *
 * Host modules read process.env at IMPORT time — a Supabase client that throws when its keys are
 * missing takes the whole lagoon down before anything renders, with an error ("process is not
 * defined") that says nothing about why. Vite's `define` does not reach files served from outside the
 * lagoon root, which is exactly where the host application's modules live, so the values are installed
 * at runtime instead. ES modules evaluate in import order, so importing this first is enough.
 */
export const ENV_SHIM = `// Installs process.env before any host module reads it. MUST be imported first — see below.
import config from '{{lagoonConfigImport}}';

const g = globalThis as unknown as { process?: { env: Record<string, string> } };
g.process = g.process ?? { env: {} };
// Declared under "env" in lagoon.config.json. The lagoon has no backend, so these only have to EXIST;
// never put a real secret here — a published lagoon is a static page anyone with the link can read.
Object.assign(g.process.env, { NODE_ENV: 'development', ...(config.env ?? {}) });
`;

/** Fixture aggregation by glob, so adding an island needs no edit here (the demo app's hand-maintained
 *  fixtures.ts drifts by construction — its own header admits the manual step). */
export const LAGOON_FIXTURES = `// Every island's lagoon fixtures, gathered by glob so adding an island is not also an edit here.
// A \`fixtures.mock.ts\` that exports \`fixtures\` / \`roles\` is picked up automatically.
import type { Fixture } from '@motu/runtime/mock';

type FixtureModule = { fixtures?: Fixture[]; roles?: string[] };

const modules = import.meta.glob<FixtureModule>({{fixturesGlob}}, { eager: true });

export const ALL_FIXTURES: Fixture[] = Object.values(modules).flatMap((m) => m.fixtures ?? []);

export const ALL_ROLES: string[] = [...new Set(Object.values(modules).flatMap((m) => m.roles ?? []))];
`;

/** The focused entry — this is what `motu island verify` drives via MOTU_TARGET. */
export const LAGOON_FOCUS_ENTRY = `{{envShim}}// Thin lagoon entry: reads the vite-injected target/fit and hands the generic lagoon harness
// (@motu/react -> bootstrapLagoon) the project's element registry, fixtures and archipelago resolver.
// All harness logic is framework-side; this file only supplies app-specific inputs.
import { bootstrapLagoon } from '@motu/react';
import { setDefaultIsolation } from '@motu/core';
import { ELEMENT_REGISTRY, ARCHIPELAGOS, getArchipelago } from '{{appPackage}}';
import css from '{{appPackage}}/styles.css?inline';
import { ALL_FIXTURES, ALL_ROLES } from '{{fixturesImport}}';
import config from '{{lagoonConfigImport}}';
// The SAME overrides the gallery entry uses. Without them the focused lagoon — the one
// \`motu island verify\` drives — ran with no region seed, so the checks asserted against defaults
// while the gallery showed seeded state.
import * as overrides from '{{overridesImport}}';
{{hostImport}}{{hostGlobalCss}}
// Injected by vite.config from the MOTU_* env (see vite.config.ts).
declare const __MOTU_TARGET__: string; // "island:{{tagPrefix}}some-tag" | "archipelago:some-id"
declare const __MOTU_FIT__: string; //    "native" | "legacy"
declare const __MOTU_FORCE_ERROR__: string; // "" | "500" | "403" — verify's error-resilience mount
declare const __MOTU_ISOLATION__: 'shadow' | 'light';

// Set BEFORE bootstrapLagoon so single-target verify exercises the project's real isolation posture.
setDefaultIsolation(__MOTU_ISOLATION__);

// The target can come from the URL (\`?target=island:x-thing\`), from the build (\`MOTU_TARGET\`), or
// from nowhere at all. The URL wins because it is what lets ONE dev server answer for every island:
// the checks navigate instead of booting a server each. Opening lagoon.html by hand passes neither,
// so fall back to the project's first archipelago rather than to a name the framework guessed.
const params = typeof location !== 'undefined' ? new URLSearchParams(location.search) : new URLSearchParams();
const targetFromUrl = params.get('target');
const target =
  targetFromUrl ||
  (typeof __MOTU_TARGET__ === 'string' && __MOTU_TARGET__) ||
  (Object.keys(ARCHIPELAGOS)[0] ? 'archipelago:' + Object.keys(ARCHIPELAGOS)[0] : '');

bootstrapLagoon({
  elements: ELEMENT_REGISTRY,
  css,
  fixtures: ALL_FIXTURES,
  roles: ALL_ROLES,
  resolveArchipelago: getArchipelago,
  // Region seeds/channels, resolved from the target — including an \`island:\` target, whose seed
  // belongs to the region that declares it.
  overrides,
  archipelagos: ARCHIPELAGOS,
  // motu's chrome wears this application's colours. Shared with the gallery through
  // lagoon.config.json so the two entries cannot disagree — override it right here when you want a
  // value the JSON should not carry, e.g. a deliberately darker shade of the brand:
  //   chrome: { ...config.chrome, primary: 'color-mix(in srgb, hsl(var(--primary)) 70%, #000)' },
  chrome: config.chrome,
  // Must match how the host application mounts islands, or this verifies a path you do not ship.
  mount: config.mount,
{{hostOption}}  target,
  fit: params.get('fit') || (typeof __MOTU_FIT__ === 'string' ? __MOTU_FIT__ : ''),
  // From the URL, like the target: the wiring/flow checks ask for 'mountpoints' so every declared
  // slot mounts regardless of where the page's own arrangement would put it.
  view: params.get('view') === 'mountpoints' ? 'mountpoints' : undefined,
  // Also from the URL, and for the same reason as the target: the error-resilience check wants ONE
  // island mounted against a failing transport, not a second dev server that differs by an env var.
  forceErrorStatus: (() => {
    const forced = params.get('forceError') || (typeof __MOTU_FORCE_ERROR__ === 'string' ? __MOTU_FORCE_ERROR__ : '');
    return forced ? Number(forced) : undefined;
  })(),
});
`;

/** `lagoon.config.json` — the project's lagoon, declared. Behaviour lives in @motu/react. */
export const LAGOON_CONFIG = `{
  "about": "The {{appPackage}} lagoon: this project's islands rendered against fixtures, with no backend, no session and no host application around them.",
  "transport": "mock",
  "defaultTheme": "motu",
{{lagoonMount}}{{lagoonChrome}}  "stations": {}
}
`;

/** For a host with shadcn-style tokens, point motu's chrome at the app's own primary by REFERENCE —
 *  no value copied here, so a rebrand in the app moves the tooling with it. */
export const LAGOON_CHROME_SHADCN = `  "chrome": {
    "primary": "hsl(var(--primary))",
    "onPrimary": "hsl(var(--primary-foreground))"
  },
`;

/** `src/lagoon.ts` — the escape hatch, empty by default. */
export const LAGOON_OVERRIDES = `// Lagoon overrides: what a JSON declaration cannot hold.
//
// Everything the lagoon DOES lives in @motu/react (\`startLagoon\`), and everything it can be TOLD is in
// ../lagoon.config.json. This file is for the rest — functions and objects — and staying empty is the
// normal case. Each export below is optional; delete what you do not use.
import type { LagoonOverrides } from '@motu/react';

// A host bridge for outward intents. The default logs them, which is usually what you want here:
// seeing "[host] navigate /x" in the console is the proof that an island emitted an intent instead of
// navigating by itself.
// export const host: LagoonOverrides['host'] = { navigate: (p) => {}, action: (n, d) => {} };

// Inbound channels per archipelago id — host signals mirrored into the store.
// export const channels: LagoonOverrides['channels'] = { someArchipelago: [] };

// Initial store contents per archipelago id, so bound islands render meaningfully on first paint.
// export const seed: LagoonOverrides['seed'] = { someArchipelago: { criteria: {} } };

// Runs before anything mounts — e.g. standing up a fake host for a foreign-framework island.
// export const setup: LagoonOverrides['setup'] = () => {};

export {};
`;

/** The gallery shim. Deliberately tiny and stable: it is wiring Vite requires in the app, nothing more. */
export const LAGOON_GALLERY_ENTRY = `{{envShim}}// The lagoon gallery entry.
//
// There is no logic here on purpose. The gallery — tide line, seam lens, archipelago switching, the
// recorded callsite frames — lives in @motu/react (\`startLagoon\`), so improvements to it arrive with
// the framework instead of needing this file regenerated. Declare the lagoon in ../lagoon.config.json;
// override behaviour in ./lagoon.ts.
//
// What stays here is only what Vite requires in the app: the build-time defines, \`import.meta.glob\`,
// the project's own registry, and the debug overlay — which @motu/react must not depend on, so the app
// hands it in.
import { startLagoon } from '@motu/react';
import { mountDebugOverlay, toggleDebugOverlay, isDebugOverlayOpen, subscribeDebugOverlay } from '@motu/debug-overlay';
import { ELEMENT_REGISTRY, ARCHIPELAGOS } from '{{appPackage}}';
import css from '{{appPackage}}/styles.css?inline';
import { ALL_FIXTURES, ALL_ROLES } from '{{fixturesImport}}';
import config from '{{lagoonConfigImport}}';
import * as overrides from '{{overridesImport}}';
{{hostImport}}{{hostGlobalCss}}
declare const __MOTU_ISOLATION__: 'shadow' | 'light';
declare const __MOTU_TRANSPORT__: string;
// "archipelago:<id>" when the artifact was built for one region; '' for the whole gallery.
declare const __MOTU_TARGET__: string;
// Present in the lagoon by default (this is the sandbox); MOTU_DEBUG=0 strips the lens entirely.
declare const __MOTU_DEBUG__: boolean;

startLagoon({
  elements: ELEMENT_REGISTRY,
  archipelagos: ARCHIPELAGOS,
  fixtures: ALL_FIXTURES,
  roles: ALL_ROLES,
  css,
  config,
  overrides,
  isolation: __MOTU_ISOLATION__,
  transport: __MOTU_TRANSPORT__,
  target: __MOTU_TARGET__,
  debug: __MOTU_DEBUG__,
  // Must match the host application (and the focused entry), or the lagoon shows a mount path the
  // project does not ship.
  mount: config.mount,
  lens: {
    mount: mountDebugOverlay,
    toggle: toggleDebugOverlay,
    isOpen: isDebugOverlayOpen,
    subscribe: subscribeDebugOverlay,
  },
  // Recorded callsite frames (\`motu archipelago record-frame\`). The glob has to be written here:
  // Vite resolves it statically, at this file's location.
  frames: import.meta.glob('{{framesGlob}}', { query: '?inline', import: 'default', eager: true }),
});
`;

// ---------------------------------------------------------------------------------------------
// Vite config — the lagoon's real contract with the CLI (these defines ARE the verify protocol)
// ---------------------------------------------------------------------------------------------

export const LAGOON_VITE_CONFIG = `import { defineConfig } from 'vite';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import react from '@vitejs/plugin-react';
{{viteHostImports}}
// The project's motu.config.json — the single declaration this lagoon reads its posture and its
// framework location from, so neither is duplicated into generated code.
const CONFIG_PATH = resolve(__dirname, '{{configFromLagoon}}');
const CONFIG = (() => {
  try {
    return JSON.parse(readFileSync(CONFIG_PATH, 'utf8'));
  } catch {
    return {};
  }
})();

// Project-wide default island isolation, so the lagoon previews the same posture as production.
const ISOLATION = CONFIG.isolation === 'light' ? 'light' : 'shadow';

// Where the motu framework checkout lives. @motu/* are unpublished workspace packages whose entry
// point is raw TypeScript, so the lagoon resolves them by path rather than through node_modules —
// which is what lets this project use motu with no install step. MOTU_ROOT overrides for CI or a
// teammate whose checkout sits elsewhere; motu.config.json's \`motuRoot\` is the committed default.
const MOTU_ROOT = process.env.MOTU_ROOT
  ? resolve(process.env.MOTU_ROOT)
  : resolve(dirname(CONFIG_PATH), CONFIG.motuRoot ?? '.');

const motu = (p) => resolve(MOTU_ROOT, p);

// The LAGOON's own declaration (next to this file). Distinct from motu.config.json above, which
// describes the project's layout; this one describes the lagoon, and carries the two things the build
// needs from it: module aliases and the browser env.
const LAGOON = (() => {
  try {
    return JSON.parse(readFileSync(resolve(__dirname, 'lagoon.config.json'), 'utf8'));
  } catch {
    return {};
  }
})();


// One-chunk build target for \`motu lagoon publish\`: 'lagoon' (focused) | 'main' (the gallery).
// Unset => the normal two-entry, code-split build.
const SINGLE_FILE =
  process.env.MOTU_SINGLEFILE === 'lagoon' ? 'lagoon' : process.env.MOTU_SINGLEFILE === 'main' ? 'main' : '';

export default defineConfig({
  plugins: [react()],
  // These defines are the contract with \`motu island verify\`, which sets the matching MOTU_* env
  // when it boots this server. Dropping one silently weakens verification — keep them in sync.
  define: {
    __MOTU_TRANSPORT__: JSON.stringify(process.env.MOTU_TRANSPORT ?? ''),
    __MOTU_TARGET__: JSON.stringify(process.env.MOTU_TARGET ?? ''),
    __MOTU_FIT__: JSON.stringify(process.env.MOTU_FIT ?? ''),
    __MOTU_FORCE_ERROR__: JSON.stringify(process.env.MOTU_FORCE_ERROR ?? ''),
    __MOTU_DEBUG__: JSON.stringify(process.env.MOTU_DEBUG !== '0'),
    __MOTU_ISOLATION__: JSON.stringify(ISOLATION),
    // The host application's modules read process.env AT IMPORT TIME — a Supabase client that throws
    // when its keys are missing is enough to take the whole lagoon down before anything renders, and
    // the error ("process is not defined") says nothing about why. There is no backend here, so the
    // values only have to exist: declare them under "env" in lagoon.config.json. Never put a real
    // secret here — the lagoon gets published as a static page.
    'process.env': JSON.stringify({ NODE_ENV: 'development', ...(LAGOON.env ?? {}) }),
  },
  resolve: {
    // One React, always. The lagoon has no React of its own so it resolves the host application's,
    // and dedupe keeps it that way through the aliased sources — two copies would break hooks in any
    // island that renders a component from the host's library.
    dedupe: ['react', 'react-dom'],
    // Array form with anchored patterns, not the object form. Vite's alias matcher is
    // exact-or-prefix-with-a-slash, which gets two things wrong here: 'pkg/styles.css?inline' never
    // matches 'pkg/styles.css' (the query is part of the id), and '@motu/runtime' happily swallows
    // '@motu/runtime/mock'. Anchored regexes make each mapping mean exactly what it says.
    alias: [
{{motuAliases}}      // Project aliases from lagoon.config.json "alias" — BEFORE the host's own '@/…' rule, because
      // the first matching entry wins and '^@/' would otherwise rewrite the specifier to the real
      // module before this ever sees it. This is the seam for standing a host module
      // down inside the lagoon — a React context whose real provider talks to a backend, a service
      // module that fetches on import — without touching the component that consumes it. Paths are
      // relative to this file. A string find matches the specifier exactly (or as a path prefix),
      // which is what a module alias wants.
      ...Object.entries(LAGOON.alias ?? {}).map(([find, replacement]) => ({
        find,
        replacement: resolve(__dirname, replacement),
      })),
{{hostAliases}}    ],
  },
{{viteCss}}  build: {
    // MOTU_SINGLEFILE=lagoon|main builds ONE entry as ONE chunk so \`motu lagoon publish\` can inline
    // the whole app into a single HTML file — nothing serves /assets/* behind a static artifact.
    ...(SINGLE_FILE ? { cssCodeSplit: false, assetsInlineLimit: 100_000_000 } : {}),
    rollupOptions: {
      input: SINGLE_FILE
        ? { [SINGLE_FILE]: resolve(__dirname, SINGLE_FILE === 'lagoon' ? 'lagoon.html' : 'index.html') }
        : { main: resolve(__dirname, 'index.html'), lagoon: resolve(__dirname, 'lagoon.html') },
      ...(SINGLE_FILE ? { output: { inlineDynamicImports: true } } : {}),
    },
  },
  server: { port: 5173, strictPort: false },
});
`;

/** The lagoon's Tailwind config: the host's, re-anchored so it works from a different directory. */
export const NEXT_TAILWIND_CONFIG = `// The lagoon's Tailwind setup — the HOST's config, with one thing changed.
//
// Tailwind resolves \`content\` globs against the current working directory, and here that is the lagoon
// rather than the app. The host's own './components/**' globs would therefore match nothing, Tailwind
// would emit no utilities at all, and every island would render unstyled — a preview that quietly lies
// about how the component looks in the app. Re-anchoring the globs on the host root fixes that, and the
// island sources are added so a class used ONLY inside an island still gets generated.
//
// Everything else (theme, plugins, dark mode, breakpoints) is inherited, so the lagoon and the app
// cannot drift apart on design tokens.
import { resolve } from 'node:path';
import hostConfig from '{{hostRootFromLagoon}}/tailwind.config';

const HOST_ROOT = resolve(__dirname, '{{hostRootFromLagoon}}');

const hostContent = Array.isArray(hostConfig.content) ? hostConfig.content : (hostConfig.content?.files ?? []);

export default {
  ...hostConfig,
  content: [
    ...hostContent.map((glob) => (typeof glob === 'string' ? resolve(HOST_ROOT, glob) : glob)),
    resolve(__dirname, '../../src/**/*.{ts,tsx}'),
  ],
};
`;

// --- host: next -------------------------------------------------------------------------------

/** Next's own modules have no meaning in a plain Vite SPA — the lagoon stubs them so a client
 *  component that links or routes still mounts. Kept deliberately small: anything an island needs
 *  beyond this is a sign it is reaching for the host instead of emitting an intent. */
export const NEXT_STUBS = `// Vite aliases point next/* here: the lagoon is a plain SPA with no Next runtime, but an island is
// still allowed to render a link or read the router. Navigation intents belong to the host bridge
// (@motu/adapter-next), so these stubs are inert on purpose — they render and no-op, they never
// navigate. If an island needs more of Next than this, it is coupling to the host too tightly.
import { createElement, forwardRef, type ComponentProps } from 'react';

export const Link = forwardRef<HTMLAnchorElement, ComponentProps<'a'> & { href?: unknown }>(
  function Link({ href, children, ...rest }, ref) {
    return createElement('a', { ...rest, ref, href: typeof href === 'string' ? href : '#' }, children);
  },
);

export const Image = forwardRef<HTMLImageElement, ComponentProps<'img'>>(function Image(props, ref) {
  return createElement('img', { ...props, ref });
});

const noop = () => {};

export function useRouter() {
  return { push: noop, replace: noop, back: noop, forward: noop, refresh: noop, prefetch: noop };
}

export function usePathname() {
  return '/';
}

export function useSearchParams() {
  return new URLSearchParams();
}

export function useParams() {
  return {} as Record<string, string>;
}

export default Link;
`;

export const NEXT_VITE_IMPORTS = `import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
`;

/** Alias fragment for a Next host: the app's own '@/…' alias plus inert next/* stubs, so the lagoon
 *  can mount components written against the host's conventions. */
export const NEXT_VITE_ALIASES = `      // The lagoon mounts components written for the Next app, so it speaks the same module language:
      // the host's '@/…' alias, and next/* mapped to inert stubs (see src/next-stubs.tsx).
      { find: /^@\\//, replacement: resolve(__dirname, '{{hostRootFromLagoon}}') + '/' },
      { find: /^next\\/link$/, replacement: resolve(__dirname, 'src/next-stubs.tsx') },
      { find: /^next\\/image$/, replacement: resolve(__dirname, 'src/next-stubs.tsx') },
      { find: /^next\\/navigation$/, replacement: resolve(__dirname, 'src/next-stubs.tsx') },
`;

/** Tailwind is the HOST's, not motu's: point postcss at the host config so an island's utility
 *  classes render in the lagoon exactly as they do in the app. */
export const NEXT_VITE_CSS = `  // Tailwind is the HOST's. It is loaded through the lagoon's own tailwind.config.ts (which extends the
  // app's) rather than imported here, because Tailwind's loader handles a config that \`require()\`s CJS
  // plugins and vite's ESM config bundling does not.
  css: {
    postcss: {
      plugins: [tailwindcss({ config: resolve(__dirname, 'tailwind.config.ts') }), autoprefixer()],
    },
  },
`;
