#!/usr/bin/env node
// Generates the typed @motu/contract from a motu-manifest.json emitted by motu-apt.
// Usage: node src/cli.mjs <path-to-motu-manifest.json> <output-dir>
//
// This closes the codegen loop: the browser contract is generated from the compiled backend, so a
// Java signature or @Roles change reshapes the TypeScript (and breaks `tsc`) instead of drifting.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const [, , manifestPath, outDir] = process.argv;
if (!manifestPath || !outDir) {
  console.error('usage: motu-codegen <motu-manifest.json> <output-dir>');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(resolve(manifestPath), 'utf8'));

const header =
  '// GENERATED by @motu/codegen from motu-manifest.json — do not edit.\n' +
  "import { call } from '@motu/runtime';\n\n";

let body = '';
const roles = {};

for (const service of manifest.services ?? []) {
  body += `export const ${service.name} = {\n`;
  for (const m of service.methods ?? []) {
    const params = (m.params ?? []).map((p) => `${p.name}: ${p.ts}`).join(', ');
    const argList = (m.params ?? []).map((p) => p.name).join(', ');
    body += `  ${m.name}: (${params}) =>\n`;
    body += `    call<${m.returns}>('${service.name}', '${m.name}', [${argList}]),\n`;
    roles[`${service.name}.${m.name}`] = m.roles ?? [];
  }
  body += '};\n\n';
}

body += `export const __roles: Record<string, string[]> = ${JSON.stringify(roles, null, 2)};\n`;

const out = resolve(outDir, 'index.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, header + body);
console.log(`motu-codegen: wrote ${out} (${(manifest.services ?? []).length} service(s))`);
