// GENERATED by `motu archipelago sync` — do not edit.
//
// Region-level deployment facts from motu.config.json. Imported for its SIDE EFFECT: it configures
// the coverage fold before any region mounts, and exports nothing.
//
// Coverage is off in motu.config.json, so this module is deliberately empty — and empty is the point.
// Nothing here names `@motu/coverage`, so no bundler ships it, while the registry's import line
// stays constant whether coverage is on or off. Turning it on never edits a hand-owned file.
export {};
