// Registry of the project's archipelagos by id, so a composition root (or the lagoon / CLI) can
// resolve one by name. `motu archipelago create` adds one import + one row here.
// Region-level deployment facts, generated by `motu archipelago sync`. Imported for its side
// effect, and FIRST: it configures the seam every archipelago below offers itself to.
import './coverage.generated';

import type { ArchipelagoConfig } from '@motu/core';
import { corpusArchipelago } from './corpus/corpus.archipelago';
import { indexArchipelago } from './index/index.archipelago';
import { reviewArchipelago } from './review/review.archipelago';
import { signinArchipelago } from './signin/signin.archipelago';

export const ARCHIPELAGOS: Record<string, ArchipelagoConfig> = {
  [corpusArchipelago.id]: corpusArchipelago,
  [indexArchipelago.id]: indexArchipelago,
  [reviewArchipelago.id]: reviewArchipelago,
  [signinArchipelago.id]: signinArchipelago,
};

/** Resolve an archipelago config by id (undefined if unknown). */
export function getArchipelago(id: string): ArchipelagoConfig | undefined {
  return ARCHIPELAGOS[id];
}
