// GENERATED by `motu island sync` — do not edit by hand.
//
// Each island's boundary, READ from the component it mounts: the props it takes, the callback props it
// calls (as event names), and the host modules it imports. Editing the component changes this file;
// editing this file changes nothing.
//
// The one part that is a decision — an event whose region name differs from the callback's — is
// declared in the island file, as `island(tag, Component, { events: { onProgress: 'week-progress' } })`,
// and baked in here so the compiler still sees literal event names.
import { islandElement } from '@motu/react';
import type { AcceptBar as C_accept_bar } from '../ui/accept-bar/AcceptBar.js';
import type { DiffViewer as C_diff_viewer } from '../ui/diff-viewer/DiffViewer.js';
import type { RepoPicker as C_repo_picker } from '../ui/repo-picker/RepoPicker.js';
import type { ShotList as C_shot_list } from '../ui/shot-list/ShotList.js';
import type { StatusSummary as C_status_summary } from '../ui/status-summary/StatusSummary.js';

export const CONTRACTS = {
  'x-accept-bar': {
    input: ['repo', 'shot', 'busy', 'shots'],
    output: { onAcceptRequested: 'accept-requested' },
    ambient: [],
  },
  'x-diff-viewer': {
    input: ['shot', 'mode', 'shots', 'shotUrl'],
    output: { onViewChanged: 'view-changed' },
    ambient: [],
  },
  'x-repo-picker': {
    input: ['repos', 'value'],
    output: { onRepoSelected: 'repo-selected' },
    ambient: [],
  },
  'x-shot-list': {
    input: ['shots', 'selected', 'busy'],
    output: { onShotSelected: 'shot-selected' },
    ambient: [],
  },
  'x-status-summary': {
    input: ['shots'],
    output: {  },
    ambient: [],
  },
} as const;

type Tag = keyof typeof CONTRACTS;

type PropsOf<C> = C extends (props: infer P, ...rest: never[]) => unknown ? NonNullable<P> : never;

/**
 * The generated contract names only props the component actually has — as a BUILD error.
 *
 * Reading the contract from the component removes the chance of transcribing it wrong, but not the
 * chance of the file going stale: rename a prop and this map still names the old one until the next
 * sync. The assertions below are what makes that a compile failure instead of an island that mounts
 * with a prop nobody fills. Type-only, so nothing here reaches a bundle.
 */
type ContractFitsComponent<C, T extends Tag> = [
  Exclude<
    (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
    keyof PropsOf<C>
  >,
] extends [never]
  ? true
  : ['contract is stale — run `motu island sync`; the component has no such prop:', Exclude<
      (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
      keyof PropsOf<C>
    >];

const _accept_bar: ContractFitsComponent<typeof C_accept_bar, 'x-accept-bar'> = true;
void _accept_bar;
const _diff_viewer: ContractFitsComponent<typeof C_diff_viewer, 'x-diff-viewer'> = true;
void _diff_viewer;
const _repo_picker: ContractFitsComponent<typeof C_repo_picker, 'x-repo-picker'> = true;
void _repo_picker;
const _shot_list: ContractFitsComponent<typeof C_shot_list, 'x-shot-list'> = true;
void _shot_list;
const _status_summary: ContractFitsComponent<typeof C_status_summary, 'x-status-summary'> = true;
void _status_summary;

/**
 * Declare an island: its tag, the component it mounts, and nothing that can be derived.
 *
 * `options.events` is read by `motu island sync` (it is what produced the output names above) and
 * applied here too, so the island is correct even before the next sync.
 */
export function island<T extends Tag>(
  tag: T,
  component: Parameters<typeof islandElement>[0]['component'],
  options?: Record<string, unknown> & { events?: Record<string, string> },
): ReturnType<typeof islandElement> & { options: { contract: (typeof CONTRACTS)[T] } } {
  const { events, ...rest } = options ?? {};
  const base = CONTRACTS[tag];
  const spec = { tag, component, options: { ...rest, contract: { ...base, output: { ...base.output, ...(events ?? {}) } } } };
  return islandElement(spec as never) as never;
}
