// GENERATED by `motu island sync` — do not edit by hand.
//
// Static imports, not a glob: this file is re-exported by the project barrel, which the host
// application imports through its own bundler, and `import.meta.glob` is Vite-only.
import type { ElementSpec } from '@motu/react';
import { element as acceptBarElement } from './accept-bar.island.js';
import { element as diffViewerElement } from './diff-viewer.island.js';
import { element as repoPickerElement } from './repo-picker.island.js';
import { element as shotListElement } from './shot-list.island.js';
import { element as statusSummaryElement } from './status-summary.island.js';

export const ELEMENT_REGISTRY: ElementSpec[] = [acceptBarElement, diffViewerElement, repoPickerElement, shotListElement, statusSummaryElement];

/**
 * Tag -> element spec, as a TYPE. Lets an archipelago check its wiring against the islands it names
 * (`RegionWiringOk`) without importing them at runtime — the values above are the registry; this is
 * the same information in a form the compiler can look up by tag.
 */
export interface ElementTypes {
  'x-accept-bar': typeof acceptBarElement;
  'x-diff-viewer': typeof diffViewerElement;
  'x-repo-picker': typeof repoPickerElement;
  'x-shot-list': typeof shotListElement;
  'x-status-summary': typeof statusSummaryElement;
}
