// GENERATED by `motu island sync` — do not edit by hand.
//
// Each island's boundary, READ from the component it mounts: the props it takes, the callback props it
// calls (as event names), and everything it reaches that is not a prop. Editing the component changes this file;
// editing this file changes nothing.
//
// The one part that is a decision — an event whose region name differs from the callback's — is
// declared in the island file, as `island(tag, Component, { events: { onProgress: 'week-progress' } })`,
// and baked in here so the compiler still sees literal event names.
import { islandElement } from '@motu/react';
import type { AcceptBar as C_accept_bar } from '@/components/review/accept-bar/AcceptBar';
import type { CorpusFilter as C_corpus_filter } from '@/components/corpus/corpus-filter';
import type { CorpusStates as C_corpus_states } from '@/components/corpus/corpus-states';
import type { DiffViewer as C_diff_viewer } from '@/components/review/diff-viewer/DiffViewer';
import type { DockRegions as C_dock_regions } from '@/components/lagoon/dock-regions';
import type { DockStates as C_dock_states } from '@/components/lagoon/dock-states';
import type { GithubSignIn as C_github_sign_in } from '@/components/auth/github-sign-in';
import type { LagoonFilter as C_lagoon_filter } from '@/components/lagoon/lagoon-filter';
import type { LagoonPalette as C_lagoon_palette } from '@/components/lagoon/lagoon-palette';
import type { LagoonRepos as C_lagoon_repos } from '@/components/lagoon/lagoon-repos';
import type { LagoonStats as C_lagoon_stats } from '@/components/lagoon/lagoon-stats';
import type { RepoPicker as C_repo_picker } from '@/components/review/repo-picker/RepoPicker';
import type { ShotList as C_shot_list } from '@/components/review/shot-list/ShotList';
import type { StatusSummary as C_status_summary } from '@/components/review/status-summary/StatusSummary';
import type { ViewerBadge as C_viewer_badge } from '@/components/lagoon/viewer-badge';

export const CONTRACTS = {
  'x-accept-bar': {
    input: ['repo', 'shot', 'busy', 'shots'],
    output: { onAcceptRequested: 'accept-requested' },
    effects: [],
  },
  'x-corpus-filter': {
    input: ['value', 'unacceptedCount'],
    output: { onFilterChange: 'filter-change' },
    effects: [],
  },
  'x-corpus-states': {
    input: ['states', 'filter', 'regionId'],
    output: {  },
    effects: [],
  },
  'x-diff-viewer': {
    input: ['shot', 'mode', 'shots', 'shotUrl'],
    output: { onViewChanged: 'view-changed' },
    effects: [],
  },
  'x-dock-regions': {
    input: ['regions', 'region'],
    output: { onRegionChange: 'region-change' },
    effects: [],
  },
  'x-dock-states': {
    input: ['states', 'flow', 'compact'],
    output: { onFlowChange: 'flow-change' },
    effects: [],
  },
  'x-github-sign-in': {
    input: ['error', 'authError', 'isSubmitting', 'returnTo', 'destination'],
    output: { onSignIn: 'sign-in' },
    effects: [],
  },
  'x-lagoon-filter': {
    input: ['query'],
    output: { onQueryChange: 'query-change' },
    effects: [],
  },
  'x-lagoon-palette': {
    input: ['repos', 'open', 'query'],
    output: { onOpenChange: 'open-change', onQueryChange: 'query-change' },
    effects: [],
  },
  'x-lagoon-repos': {
    input: ['repos', 'cap', 'query'],
    output: {  },
    effects: [],
  },
  'x-lagoon-stats': {
    input: ['stats'],
    output: {  },
    effects: [],
  },
  'x-repo-picker': {
    input: ['repos', 'value', 'shots'],
    output: { onRepoSelected: 'repo-selected' },
    effects: [],
  },
  'x-shot-list': {
    input: ['shots', 'selected', 'busy'],
    output: { onShotSelected: 'shot-selected' },
    effects: [],
  },
  'x-status-summary': {
    input: ['shots'],
    output: {  },
    effects: [],
  },
  'x-viewer-badge': {
    input: ['viewer'],
    output: {  },
    effects: [],
  },
} as const;

type Tag = keyof typeof CONTRACTS;

type PropsOf<C> = C extends (props: infer P, ...rest: never[]) => unknown ? NonNullable<P> : never;

/**
 * The generated contract names only props the component actually has — as a BUILD error.
 *
 * Reading the contract from the component removes the chance of transcribing it wrong, but not the
 * chance of the file going stale: rename a prop and this map still names the old one until the next
 * sync. The assertions below are what makes that a compile failure instead of an island that mounts
 * with a prop nobody fills. Type-only, so nothing here reaches a bundle.
 */
type ContractFitsComponent<C, T extends Tag> = [
  Exclude<
    (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
    keyof PropsOf<C>
  >,
] extends [never]
  ? true
  : ['contract is stale — run `motu island sync`; the component has no such prop:', Exclude<
      (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
      keyof PropsOf<C>
    >];

const _accept_bar: ContractFitsComponent<typeof C_accept_bar, 'x-accept-bar'> = true;
void _accept_bar;
const _corpus_filter: ContractFitsComponent<typeof C_corpus_filter, 'x-corpus-filter'> = true;
void _corpus_filter;
const _corpus_states: ContractFitsComponent<typeof C_corpus_states, 'x-corpus-states'> = true;
void _corpus_states;
const _diff_viewer: ContractFitsComponent<typeof C_diff_viewer, 'x-diff-viewer'> = true;
void _diff_viewer;
const _dock_regions: ContractFitsComponent<typeof C_dock_regions, 'x-dock-regions'> = true;
void _dock_regions;
const _dock_states: ContractFitsComponent<typeof C_dock_states, 'x-dock-states'> = true;
void _dock_states;
const _github_sign_in: ContractFitsComponent<typeof C_github_sign_in, 'x-github-sign-in'> = true;
void _github_sign_in;
const _lagoon_filter: ContractFitsComponent<typeof C_lagoon_filter, 'x-lagoon-filter'> = true;
void _lagoon_filter;
const _lagoon_palette: ContractFitsComponent<typeof C_lagoon_palette, 'x-lagoon-palette'> = true;
void _lagoon_palette;
const _lagoon_repos: ContractFitsComponent<typeof C_lagoon_repos, 'x-lagoon-repos'> = true;
void _lagoon_repos;
const _lagoon_stats: ContractFitsComponent<typeof C_lagoon_stats, 'x-lagoon-stats'> = true;
void _lagoon_stats;
const _repo_picker: ContractFitsComponent<typeof C_repo_picker, 'x-repo-picker'> = true;
void _repo_picker;
const _shot_list: ContractFitsComponent<typeof C_shot_list, 'x-shot-list'> = true;
void _shot_list;
const _status_summary: ContractFitsComponent<typeof C_status_summary, 'x-status-summary'> = true;
void _status_summary;
const _viewer_badge: ContractFitsComponent<typeof C_viewer_badge, 'x-viewer-badge'> = true;
void _viewer_badge;

/**
 * Declare an island: its tag, the component it mounts, and nothing that can be derived.
 *
 * `options.events` is read by `motu island sync` (it is what produced the output names above) and
 * applied here too, so the island is correct even before the next sync.
 */
export function island<T extends Tag>(
  tag: T,
  component: Parameters<typeof islandElement>[0]['component'],
  options?: Record<string, unknown> & { events?: Record<string, string> },
): ReturnType<typeof islandElement> & { options: { contract: (typeof CONTRACTS)[T] } } {
  const { events, ...rest } = options ?? {};
  const base = CONTRACTS[tag];
  const spec = { tag, component, options: { ...rest, contract: { ...base, output: { ...base.output, ...(events ?? {}) } } } };
  return islandElement(spec as never) as never;
}
