// GENERATED by `motu island sync` — do not edit by hand.
//
// Static imports, not a glob: this file is re-exported by the project barrel, which the host
// application imports through its own bundler, and `import.meta.glob` is Vite-only.
import type { ElementSpec } from '@motu/react';
import { setDefaultIsolation } from '@motu/core';
import { element as acceptBarElement } from './accept-bar.island';
import { element as corpusFilterElement } from './corpus-filter.island';
import { element as corpusStatesElement } from './corpus-states.island';
import { element as diffViewerElement } from './diff-viewer.island';
import { element as dockRegionsElement } from './dock-regions.island';
import { element as dockStatesElement } from './dock-states.island';
import { element as githubSignInElement } from './github-sign-in.island';
import { element as lagoonFilterElement } from './lagoon-filter.island';
import { element as lagoonPaletteElement } from './lagoon-palette.island';
import { element as lagoonReposElement } from './lagoon-repos.island';
import { element as lagoonStatsElement } from './lagoon-stats.island';
import { element as repoPickerElement } from './repo-picker.island';
import { element as shotListElement } from './shot-list.island';
import { element as statusSummaryElement } from './status-summary.island';
import { element as viewerBadgeElement } from './viewer-badge.island';

// ISOLATION, from motu.config.json, applied by IMPORTING this file.
//
// The lagoon has always had it — its root is scaffolded with `setDefaultIsolation(__MOTU_ISOLATION__)`
// — and a host application had no way to say it at all: `registerElements` takes css and a theme and
// nothing else. So a project declaring `light` previewed in light DOM and SHIPPED in shadow, which
// changes whether the host's own stylesheet reaches the island. Approving a baseline then means
// approving something the page does not render.
//
// Set here rather than as an argument to `registerElements` so no host has to repeat the value and
// no host can disagree with the config: importing the registry is already what a host does, and this
// file is generated, so a stale copy is caught the same way every other drift in it is.
setDefaultIsolation('light');
export const ELEMENT_REGISTRY: ElementSpec[] = [acceptBarElement, corpusFilterElement, corpusStatesElement, diffViewerElement, dockRegionsElement, dockStatesElement, githubSignInElement, lagoonFilterElement, lagoonPaletteElement, lagoonReposElement, lagoonStatsElement, repoPickerElement, shotListElement, statusSummaryElement, viewerBadgeElement];

/**
 * Tag -> element spec, as a TYPE. Lets an archipelago check its wiring against the islands it names
 * (`RegionWiringOk`) without importing them at runtime — the values above are the registry; this is
 * the same information in a form the compiler can look up by tag.
 */
export interface ElementTypes {
  'x-accept-bar': typeof acceptBarElement;
  'x-corpus-filter': typeof corpusFilterElement;
  'x-corpus-states': typeof corpusStatesElement;
  'x-diff-viewer': typeof diffViewerElement;
  'x-dock-regions': typeof dockRegionsElement;
  'x-dock-states': typeof dockStatesElement;
  'x-github-sign-in': typeof githubSignInElement;
  'x-lagoon-filter': typeof lagoonFilterElement;
  'x-lagoon-palette': typeof lagoonPaletteElement;
  'x-lagoon-repos': typeof lagoonReposElement;
  'x-lagoon-stats': typeof lagoonStatsElement;
  'x-repo-picker': typeof repoPickerElement;
  'x-shot-list': typeof shotListElement;
  'x-status-summary': typeof statusSummaryElement;
  'x-viewer-badge': typeof viewerBadgeElement;
}
