// AngularJS-native channels. They depend only on AngularJS primitives ($http, scopes) — not on any
// form-widget library or UI toolkit — so any AngularJS host can use them.

import type { Store, Channel } from '@motu/core';
import { motuAngularInjector } from './host.js';

type Matcher = RegExp | ((url: string, method: string) => boolean);

function matches(m: Matcher, url: string, method: string): boolean {
  return typeof m === 'function' ? m(url, method) : m.test(url);
}

function angular(): any {
  return (window as unknown as { angular?: any }).angular;
}

export interface HttpChannelSpec {
  /** Which requests to mirror (by URL, and optionally method). */
  match: Matcher;
  /** Called with the request body before it goes out (e.g. legacy search criteria). */
  onRequest?: (info: { url: string; method: string; body: unknown }, store: Store) => void;
  /** Called with the response body when it returns (e.g. the resulting page). */
  onResponse?: (info: { url: string; method: string; body: unknown; response: unknown }, store: Store) => void;
  /** AngularJS module to register the interceptor on. Default 'app'. */
  module?: string;
}

/**
 * A network channel: an AngularJS $http interceptor that mirrors matching requests/responses into
 * the store. it only needs the host to call $http against a known URL. Must be
 * installed before the AngularJS app bootstraps (as bridge.js is).
 */
export function angularHttpChannel(spec: HttpChannelSpec): Channel {
  return ({ store }) => {
    const ng = angular();
    if (!ng) {
      console.warn('motu: angularHttpChannel requires AngularJS on the page');
      return;
    }
    ng.module(spec.module ?? 'app').config([
      '$httpProvider',
      ($httpProvider: any) => {
        $httpProvider.interceptors.push(() => ({
          request(config: any) {
            try {
              const url = config?.url ?? '';
              if (url && matches(spec.match, url, config?.method ?? 'GET')) {
                spec.onRequest?.({ url, method: config?.method ?? 'GET', body: config?.data }, store);
              }
            } catch {
              /* never break the host's request pipeline */
            }
            return config;
          },
          response(response: any) {
            try {
              const cfg = response?.config;
              const url = cfg?.url ?? '';
              if (url && matches(spec.match, url, cfg?.method ?? 'GET')) {
                spec.onResponse?.(
                  { url, method: cfg?.method ?? 'GET', body: cfg?.data, response: response?.data },
                  store,
                );
              }
            } catch {
              /* never break the host's response pipeline */
            }
            return response;
          },
        }));
      },
    ]);
    // module.config registrations are not removable; nothing to dispose.
  };
}

export interface ScopeChannelSpec {
  /** Element whose AngularJS scope holds the value. */
  selector: string;
  /** Scope expression to watch, e.g. 'search'. */
  watch: string;
  /** Store key to write. */
  into: string;
  /** Deep-watch objects (default true). */
  deep?: boolean;
  /** Debounce writes by this many ms — for real-time typing, avoids a store write per keystroke. */
  debounce?: number;
  /** Map the watched value before storing (e.g. prune a legacy model to the motu criteria keys). */
  transform?: (value: unknown) => unknown;
}

/**
 * A state channel: watches an AngularJS scope expression and mirrors it into the store. Works for any
 * ng-model (hand-written or generated by a form-widget library). The target may not exist yet (route not loaded), so it
 * attaches once the element appears.
 */
export function angularScopeChannel(spec: ScopeChannelSpec): Channel {
  return ({ store }) => {
    const ng = angular();
    if (!ng) {
      console.warn('motu: angularScopeChannel requires AngularJS on the page');
      return;
    }
    let unwatch: (() => void) | undefined;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const write = (v: unknown) => store.set(spec.into, spec.transform ? spec.transform(v) : v);
    const onChange = (v: unknown) => {
      if (!spec.debounce) {
        write(v);
        return;
      }
      if (timer) clearTimeout(timer);
      timer = setTimeout(() => write(v), spec.debounce);
    };
    const attach = (): boolean => {
      const el = document.querySelector(spec.selector);
      if (!el) return false;
      const scope = ng.element(el).scope();
      if (!scope) return false;
      unwatch = scope.$watch(spec.watch, onChange, spec.deep ?? true);
      return true;
    };
    if (attach()) {
      return () => {
        if (timer) clearTimeout(timer);
        unwatch?.();
      };
    }
    const obs = new MutationObserver(() => {
      if (attach()) obs.disconnect();
    });
    obs.observe(document.documentElement, { childList: true, subtree: true });
    return () => {
      obs.disconnect();
      if (timer) clearTimeout(timer);
      unwatch?.();
    };
  };
}

export interface HostScopeChannelSpec {
  /** Scope PROPERTY to locate anywhere on the $rootScope tree, e.g. 'hostSearchConfig'. */
  key: string;
  /** Store key to write. */
  into: string;
  /** Map the value before storing. */
  transform?: (value: unknown) => unknown;
  /** App module to hook when the host hasn't bootstrapped yet (embedded). Default 'app'. */
  module?: string;
}

/**
 * A state channel that mirrors a host scope PROPERTY into the store, locating it anywhere on the
 * $rootScope tree. Unlike angularScopeChannel it needs no selector and no element scope data (so it
 * works with debugInfoEnabled(false) and when the value lives on a child controller scope, not
 * $rootScope) — use it for host data that isn't tied to a known element, e.g. a field-schema config a
 * controller builds asynchronously.
 *
 * Resolves the host two ways so the same wiring runs in both modes: the motu-provided injector when a
 * host is already bootstrapped (the lagoon), else — embedded, where bridge.js installs BEFORE the app
 * boots and the app bootstraps on an inner element (so document.body has no injector) — it hooks the
 * app module's run block, exactly like angularHttpChannel hooks .config. Writes once the property
 * appears (and on later changes).
 */
export function angularHostScopeChannel(spec: HostScopeChannelSpec): Channel {
  return ({ store }) => {
    const ng = angular();
    if (!ng) {
      console.warn('motu: angularHostScopeChannel requires AngularJS on the page');
      return;
    }
    const find = (s: any): unknown => {
      if (!s) return undefined;
      if (Object.prototype.hasOwnProperty.call(s, spec.key)) return s[spec.key];
      for (let child = s.$$childHead; child; child = child.$$nextSibling) {
        const found = find(child);
        if (found !== undefined) return found;
      }
      return undefined;
    };
    // Reference watch: the config object is stable once built, so this fires once (absent -> present),
    // then deregisters so we don't tree-walk every digest for the life of the app.
    const watch = (rootScope: any) => {
      const stop = rootScope.$watch(
        () => find(rootScope),
        (v: unknown) => {
          if (v == null) return;
          store.set(spec.into, spec.transform ? spec.transform(v) : v);
          stop();
        },
      );
      return stop;
    };

    // Lagoon (or any host already bootstrapped when channels install): watch its live $rootScope now.
    const hostInjector = motuAngularInjector();
    if (hostInjector) return watch(hostInjector.get('$rootScope'));

    // Embedded: the app isn't bootstrapped yet — register a run block so we get the real $rootScope
    // once it boots. (module.run registrations are not removable, so there's nothing to dispose.)
    ng.module(spec.module ?? 'app').run(['$rootScope', watch]);
  };
}
