// GENERATED by `motu island sync` — do not edit by hand.
//
// Each island's boundary, READ from the component it mounts: the props it takes, the callback props it
// calls (as event names), and everything it reaches that is not a prop. Editing the component changes this file;
// editing this file changes nothing.
//
// The one part that is a decision — an event whose region name differs from the callback's — is
// declared in the island file, as `island(tag, Component, { events: { onProgress: 'week-progress' } })`,
// and baked in here so the compiler still sees literal event names.
import { islandElement } from '@motu/react';
import type { CompanyLookup as C_company_lookup } from '../ui/company-lookup/CompanyLookup.js';
import type { MemberActions as C_member_actions } from '../ui/member-actions/MemberActions.js';
import type { MemberCard as C_member_card } from '../ui/member-card/MemberCard.js';
import type { MemberFilterChips as C_member_filter_chips } from '../ui/member-filter-chips/MemberFilterChips.js';
import type { MemberForm as C_member_form } from '../ui/member-form/MemberForm.js';
import type { MemberHeader as C_member_header } from '../ui/member-header/MemberHeader.js';
import type { MemberResults as C_member_results } from '../ui/member-results/MemberResults.js';
import type { OrgHeadcount as C_org_headcount } from '../ui/org-headcount/OrgHeadcount.js';
import type { OrgPeople as C_org_people } from '../ui/org-people/OrgPeople.js';
import type { OrgPerson as C_org_person } from '../ui/org-person/OrgPerson.js';
import type { OrgTree as C_org_tree } from '../ui/org-tree/OrgTree.js';
import type { ProfileHero as C_profile_hero } from '../ui/profile-hero/ProfileHero.js';
import type { SelectedCompany as C_selected_company } from '../ui/selected-company/SelectedCompany.js';

export const CONTRACTS = {
  'x-company-lookup': {
    input: ['prefix'],
    output: { onCompanySelected: 'company-selected' },
    effects: [],
  },
  'x-member-actions': {
    input: [],
    output: { onNew: 'new', onPaste: 'paste' },
    effects: [],
  },
  'x-member-card': {
    input: ['draft', 'loading', 'showActions', 'layout'],
    output: {  },
    effects: [],
  },
  'x-member-filter-chips': {
    input: ['criteria'],
    output: { onCriteriaChanged: 'criteria-changed' },
    effects: [],
  },
  'x-member-form': {
    input: ['draft', 'chapters'],
    output: { onDraftChanged: 'member-draft', onReset: 'member-reset' },
    effects: [],
  },
  'x-member-header': {
    input: ['heading', 'subtitle', 'badge'],
    output: {  },
    effects: [],
  },
  'x-member-results': {
    input: ['criteria', 'members'],
    output: { onCount: 'count', onPage: 'page', onSelected: 'selected', onOpen: 'open' },
    effects: [],
  },
  'x-member-search-ng': {
    input: [],
    output: {  },
    effects: [],
  },
  'x-org-headcount': {
    input: ['chart', 'department', 'companyLabel'],
    output: {  },
    effects: [],
  },
  'x-org-people': {
    input: ['department', 'person'],
    output: { onPersonSelected: 'person-selected' },
    effects: [],
  },
  'x-org-person': {
    input: ['person', 'department'],
    output: {  },
    effects: [],
  },
  'x-org-tree': {
    input: ['chart', 'department', 'companyLabel'],
    output: { onDepartmentSelected: 'department-selected' },
    effects: [],
  },
  'x-profile-hero': {
    input: ['member', 'calendar', 'loading'],
    output: { onBack: 'profile-back' },
    effects: [],
  },
  'x-selected-company': {
    input: ['company'],
    output: {  },
    effects: [],
  },
} as const;

type Tag = keyof typeof CONTRACTS;

type PropsOf<C> = C extends (props: infer P, ...rest: never[]) => unknown ? NonNullable<P> : never;

/**
 * The generated contract names only props the component actually has — as a BUILD error.
 *
 * Reading the contract from the component removes the chance of transcribing it wrong, but not the
 * chance of the file going stale: rename a prop and this map still names the old one until the next
 * sync. The assertions below are what makes that a compile failure instead of an island that mounts
 * with a prop nobody fills. Type-only, so nothing here reaches a bundle.
 */
type ContractFitsComponent<C, T extends Tag> = [
  Exclude<
    (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
    keyof PropsOf<C>
  >,
] extends [never]
  ? true
  : ['contract is stale — run `motu island sync`; the component has no such prop:', Exclude<
      (typeof CONTRACTS)[T]['input'][number] | keyof (typeof CONTRACTS)[T]['output'],
      keyof PropsOf<C>
    >];

const _company_lookup: ContractFitsComponent<typeof C_company_lookup, 'x-company-lookup'> = true;
void _company_lookup;
const _member_actions: ContractFitsComponent<typeof C_member_actions, 'x-member-actions'> = true;
void _member_actions;
const _member_card: ContractFitsComponent<typeof C_member_card, 'x-member-card'> = true;
void _member_card;
const _member_filter_chips: ContractFitsComponent<typeof C_member_filter_chips, 'x-member-filter-chips'> = true;
void _member_filter_chips;
const _member_form: ContractFitsComponent<typeof C_member_form, 'x-member-form'> = true;
void _member_form;
const _member_header: ContractFitsComponent<typeof C_member_header, 'x-member-header'> = true;
void _member_header;
const _member_results: ContractFitsComponent<typeof C_member_results, 'x-member-results'> = true;
void _member_results;
const _org_headcount: ContractFitsComponent<typeof C_org_headcount, 'x-org-headcount'> = true;
void _org_headcount;
const _org_people: ContractFitsComponent<typeof C_org_people, 'x-org-people'> = true;
void _org_people;
const _org_person: ContractFitsComponent<typeof C_org_person, 'x-org-person'> = true;
void _org_person;
const _org_tree: ContractFitsComponent<typeof C_org_tree, 'x-org-tree'> = true;
void _org_tree;
const _profile_hero: ContractFitsComponent<typeof C_profile_hero, 'x-profile-hero'> = true;
void _profile_hero;
const _selected_company: ContractFitsComponent<typeof C_selected_company, 'x-selected-company'> = true;
void _selected_company;

/**
 * Declare an island: its tag, the component it mounts, and nothing that can be derived.
 *
 * `options.events` is read by `motu island sync` (it is what produced the output names above) and
 * applied here too, so the island is correct even before the next sync.
 */
export function island<T extends Tag>(
  tag: T,
  component: Parameters<typeof islandElement>[0]['component'],
  options?: Record<string, unknown> & { events?: Record<string, string> },
): ReturnType<typeof islandElement> & { options: { contract: (typeof CONTRACTS)[T] } } {
  const { events, ...rest } = options ?? {};
  const base = CONTRACTS[tag];
  const spec = { tag, component, options: { ...rest, contract: { ...base, output: { ...base.output, ...(events ?? {}) } } } };
  return islandElement(spec as never) as never;
}
