// GENERATED by `motu island sync` — do not edit by hand.
//
// Static imports, not a glob: this file is re-exported by the project barrel, which the host
// application imports through its own bundler, and `import.meta.glob` is Vite-only.
import type { ElementSpec } from '@motu/react';
import { setDefaultIsolation } from '@motu/core';
import { companyLookupElement } from './company-lookup/element';
import { memberActionsElement } from './member-actions/element';
import { memberCardElement } from './member-card/element';
import { memberFilterChipsElement } from './member-filter-chips/element';
import { memberFormElement } from './member-form/element';
import { memberHeaderElement } from './member-header/element';
import { memberResultsElement } from './member-results/element';
import { memberSearchNgElement } from './member-search-ng/element';
import { orgHeadcountElement } from './org-headcount/element';
import { orgPeopleElement } from './org-people/element';
import { orgPersonElement } from './org-person/element';
import { orgTreeElement } from './org-tree/element';
import { profileHeroElement } from './profile-hero/element';
import { selectedCompanyElement } from './selected-company/element';

// ISOLATION, from motu.config.json, applied by IMPORTING this file.
//
// The lagoon has always had it — its root is scaffolded with `setDefaultIsolation(__MOTU_ISOLATION__)`
// — and a host application had no way to say it at all: `registerElements` takes css and a theme and
// nothing else. So a project declaring `light` previewed in light DOM and SHIPPED in shadow, which
// changes whether the host's own stylesheet reaches the island. Approving a baseline then means
// approving something the page does not render.
//
// Set here rather than as an argument to `registerElements` so no host has to repeat the value and
// no host can disagree with the config: importing the registry is already what a host does, and this
// file is generated, so a stale copy is caught the same way every other drift in it is.
setDefaultIsolation('light');
export const ELEMENT_REGISTRY: ElementSpec[] = [companyLookupElement, memberActionsElement, memberCardElement, memberFilterChipsElement, memberFormElement, memberHeaderElement, memberResultsElement, memberSearchNgElement, orgHeadcountElement, orgPeopleElement, orgPersonElement, orgTreeElement, profileHeroElement, selectedCompanyElement];

/**
 * Tag -> element spec, as a TYPE. Lets an archipelago check its wiring against the islands it names
 * (`RegionWiringOk`) without importing them at runtime — the values above are the registry; this is
 * the same information in a form the compiler can look up by tag.
 */
export interface ElementTypes {
  'x-company-lookup': typeof companyLookupElement;
  'x-member-actions': typeof memberActionsElement;
  'x-member-card': typeof memberCardElement;
  'x-member-filter-chips': typeof memberFilterChipsElement;
  'x-member-form': typeof memberFormElement;
  'x-member-header': typeof memberHeaderElement;
  'x-member-results': typeof memberResultsElement;
  'x-member-search-ng': typeof memberSearchNgElement;
  'x-org-headcount': typeof orgHeadcountElement;
  'x-org-people': typeof orgPeopleElement;
  'x-org-person': typeof orgPersonElement;
  'x-org-tree': typeof orgTreeElement;
  'x-profile-hero': typeof profileHeroElement;
  'x-selected-company': typeof selectedCompanyElement;
}
